/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I | undefined, U>
	: ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
	string,
	bigint | number | string,
	bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
	[x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Bookmarks {
	contest_id: number;
	created_at: Generated<Timestamp>;
	id: Generated<number>;
	user_id: Int8;
}

export interface Contests {
	announced: Generated<boolean>;
	anonymous: boolean;
	cover_image: Json | null;
	created_at: Generated<Timestamp>;
	date_end: number;
	description: string;
	fee: number;
	fee_wallet: string | null;
	id: Generated<number>;
	image: string | null;
	instruction: string | null;
	owner_id: Int8;
	prize: string | null;
	results: Generated<Json>;
	slug: string;
	slug_moderator: string;
	theme: Json | null;
	title: string;
	verified: Generated<boolean>;
}

export interface Moderators {
	contest_id: number;
	created_at: Generated<Timestamp>;
	id: Generated<number>;
	user_id: Int8;
}

export interface Settings {
	id: Generated<number>;
	meta: string;
	value: string | null;
}

export interface Submissions {
	contest_id: number;
	created_at: Generated<Timestamp>;
	id: Generated<number>;
	submission: Json;
	user_id: Int8;
}

export interface Users {
	anonymous_profile: Json;
	created_at: Generated<Timestamp>;
	first_name: string;
	id: Generated<Int8>;
	language: Generated<string>;
	last_name: string | null;
	premium: Generated<boolean>;
	profile_photo: string | null;
	user_id: Int8;
	username: string | null;
}

export interface Votes {
	created_at: Generated<Timestamp>;
	id: Generated<number>;
	submission_id: Int8 | null;
	user_id: Int8;
	vote: string | null;
}

export interface DB {
	bookmarks: Bookmarks;
	contests: Contests;
	moderators: Moderators;
	settings: Settings;
	submissions: Submissions;
	users: Users;
	votes: Votes;
}
